package:
  name: hw
  version: 1.0.0

source:
  path: ..

build:
  noarch_python: True
  number: 0

requirements:
  build:
    - python
    - pyqt
  run:
    - python
    - pyqt
    
test:
  imports:
    - hw
