package:
  name: hw
  version: 1.0.0

source:
  path: ..

build:
  number: 0
  features:
    - vc14     # [win and py35]
    - vc10     # [win and py34]
    - vc9      # [win and py27]

requirements:
  build:
    - python
  run:
    - python
    
test:
  imports:
    - hw
